DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS events;

CREATE TABLE user (
  userid INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE events (
  eventid INTEGER PRIMARY KEY AUTOINCREMENT,
  eventtitle TEXT NOT NULL,
  eventdate DATETIME NOT NULL,
  eventlevel TEXT NOT NULL,
  
  eventdesc TEXT NOT NULL,
  authorid INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (authorid) REFERENCES user (userid)
);
